includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to be validated. Voting is neutral, only comments with results are sent.
    failure-message: Build failed. For rechecking only on the Hyper-V CI, add a review comment with check hyper-v
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          comment_filter: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(check hyper-v)
    dequeue-on-new-patchset: true

jobs:
  - name: ^.*$
    parameter-function: set_log_url
  - name: noop
    voting: false


projects:
  - name: openstack-dev/ci-sandbox
    check:
      - noop

